### ISSUE TITLE
Validate that tests work

### ISSUE THREAD

**Issue by Guang-yi** [rachelee728/React#3]
RUN `npm test`
Exit criteria: Take a screenshot of the output. Make sure it's all green.
Resources: https://create-react-app.dev/docs/running-tests

**Comment by rachelee728** [comment]
<img width="356" alt="Screen Shot 2020-02-25 at 12 33 32 PM" src="https://user-images.githubusercontent.com/16144774/75272008-24775780-57cb-11ea-913a-43b6b7a80cbf.png">

**Comment by Guang-yi** [comment]
Nice
